

The study will involve adding features to Hackerbot, including the ability to use LLMs to generate responses. Prompts, models, and other parameters will be configurable through files generated by SecGen.

// Cliffe: move reporting on your progress to a later section. 
Development and testing of artifacts for the hackerbot study is already well underway with a functional implementation. It shall be live tested in the coming semester on students in incident response, and the next semester with systems security.